/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../components/AppLink.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    GlobalLoading: typeof import('./../components/GlobalLoading.vue')['default']
    MenuTree: typeof import('./../components/MenuTree.vue')['default']
    ResponsiveCard: typeof import('./../components/ResponsiveCard.vue')['default']
    ResponsiveContainer: typeof import('./../components/ResponsiveContainer.vue')['default']
    RolePermissionView: typeof import('./../components/RolePermissionView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./../components/ScrollPane.vue')['default']
    SidebarItem: typeof import('./../components/SidebarItem.vue')['default']
    TagsView: typeof import('./../components/TagsView.vue')['default']
  }
}
